version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANJSON5Project
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.mjanjson5.documenttypes:request
  packages:
  - name: MJANJSON5Project
    version: "1.0"
- serviceName: project.mjanjson5.integrations:jsonIssue
  packages:
  - name: MJANJSON5Project
    version: "1.0"
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
